services:
  payment-db:
    image: mongo:8.0
    container_name: ${DB_CONTAINER_NAME}

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

    ports:
      - "${DB_PORT}:27017"

    volumes:
      - payment-db-data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--username",
          "${DB_USERNAME}",
          "--password",
          "${DB_PASSWORD}",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping').ok"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  payment-db-data: